### ISSUE TITLE
Missing dependency: Problems installing

### ISSUE THREAD

**Issue by JoeSgambellone** [hviidhenrik/SPC#1]
Hi. I tried installing your SPC package and ran into issues. First, it failed because I didn't have ez_setup, so I installed it (it's missing from your dependency list). 

Next, I'm getting this error:

`py -m pip install spc`
Defaulting to user installation because normal site-packages is not writeable
Collecting spc
  Using cached spc-0.3.tar.gz (4.3 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
      Traceback (most recent call last):
        File "C:\Users\MyName\AppData\Roaming\Python\Python39\site-packages\ez_setup.py", line 143, in use_setuptools
          raise ImportError
      ImportError
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\MyName\AppData\Local\Temp\pip-install-nb975t5c\spc_32249290e99b4285ad30ce23b182b9dc\setup.py", line 4, in <module>
          use_setuptools()
        File "C:\Users\MyName\AppData\Roaming\Python\Python39\site-packages\ez_setup.py", line 145, in use_setuptools
          return _do_download(version, download_base, to_dir, download_delay)
        File "C:\Users\MyName\AppData\Roaming\Python\Python39\site-packages\ez_setup.py", line 123, in _do_download
          tarball = download_setuptools(version, download_base,
        File "C:\Users\MyName\AppData\Roaming\Python\Python39\site-packages\ez_setup.py", line 193, in download_setuptools
          src = urlopen(url)
        File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\urllib\request.py", line 214, in urlopen
          return opener.open(url, data, timeout)
        File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\urllib\request.py", line 523, in open
          response = meth(req, response)
        File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\urllib\request.py", line 632, in http_response
          response = self.parent.error(
        File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\urllib\request.py", line 561, in error
          return self._call_chain(*args)
        File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\urllib\request.py", line 494, in _call_chain
          result = func(*args)
        File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\urllib\request.py", line 641, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 403: SSL is required
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I updated setuptools, but that didn't seem to help. Thank you for writing this package and I hope to get it going soon. Thanks!

**Comment by hviidhenrik** [comment]
Hi, thanks for your detailed description and apologies for my late reply. I suggest you look at this repo instead: https://github.com/hviidhenrik/pySPC - it is more updated. I no longer maintain the first one, as it was a project I used mainly for my PhD. I hope you make it work, and thanks for your interest in SPC!
